install apple-gcc42
install brew-cask
install couchdb
install elixir
install fish
install go
install help2man
install imagemagick
install jsonpp
install libksba
install libxslt
install libyaml
install memcached
install mongodb
install mysql
install node
install python
install qt
install rbenv --HEAD
install rbenv-readline
install redis
install ssh-copy-id
install tcl-tk
install tesseract
install the_silver_searcher
install tig
install tmux
install tree
install wget
install wry
install wxmac
